// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMWDwPuN3nCde6BXCPTfAO873l_7sTdHQ',
    appId: '1:124128929881:web:6716f89fe565dab548a948',
    messagingSenderId: '124128929881',
    projectId: 'graduation-5017a',
    authDomain: 'graduation-5017a.firebaseapp.com',
    storageBucket: 'graduation-5017a.firebasestorage.app',
    measurementId: 'G-EKFHGS7YRQ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVaVok7JiJqkU7y9tCxzyA1TZx7KpYl8Y',
    appId: '1:124128929881:ios:7867b1f18217e84048a948',
    messagingSenderId: '124128929881',
    projectId: 'graduation-5017a',
    storageBucket: 'graduation-5017a.firebasestorage.app',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVaVok7JiJqkU7y9tCxzyA1TZx7KpYl8Y',
    appId: '1:124128929881:ios:7867b1f18217e84048a948',
    messagingSenderId: '124128929881',
    projectId: 'graduation-5017a',
    storageBucket: 'graduation-5017a.firebasestorage.app',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADo0AantVYZj4Yd9JkP-imisxhHAg_bJM',
    appId: '1:124128929881:android:f53ac96426e7f3e348a948',
    messagingSenderId: '124128929881',
    projectId: 'graduation-5017a',
    storageBucket: 'graduation-5017a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMWDwPuN3nCde6BXCPTfAO873l_7sTdHQ',
    appId: '1:124128929881:web:2636ea443b4311d548a948',
    messagingSenderId: '124128929881',
    projectId: 'graduation-5017a',
    authDomain: 'graduation-5017a.firebaseapp.com',
    storageBucket: 'graduation-5017a.firebasestorage.app',
    measurementId: 'G-T1DYC75Q71',
  );

}